# -*- coding: utf-8 -*-
"""Reto 1_González González Sergio Erick.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gK-Tcb9cQrhPgzpf5tqiu7SXiDI3pXNK

#**Reto 1: Humano vs Máquina - La Batalla de los Pingüinos**

Alumno: González González Sergio Erick

#Configuración Inicial
"""

# ═══════════════════════════════════════════════════════════════════════════
# CONFIGURACIÓN DE LA ESTACIÓN PALMER - NO MODIFICAR
# ═══════════════════════════════════════════════════════════════════════════

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Configuración visual
plt.style.use('seaborn-v0_8-whitegrid')
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 11
np.random.seed(42)

# Colores oficiales de cada especie (inspirados en sus características)
COLORES_ESPECIES = {
    'Adelie': '#FF6B6B',      # Rojo coral
    'Chinstrap': '#4ECDC4',   # Turquesa
    'Gentoo': '#45B7D1'       # Azul cielo
}

print("╔═══════════════════════════════════════════════════════════════╗")
print("║     🐧 ESTACIÓN PALMER - SISTEMA DE CLASIFICACIÓN v2.0 🐧    ║")
print("║                                                               ║")
print("║   Bibliotecas cargadas correctamente                          ║")
print("║   Modo: HUMANO VS MÁQUINA                                     ║")
print("║                                                               ║")
print("╚═══════════════════════════════════════════════════════════════╝")

# ═══════════════════════════════════════════════════════════════════════════
# CARGAR DATOS DE CAMPO - Dataset Palmer Penguins
# ═══════════════════════════════════════════════════════════════════════════

# Cargar el dataset de pingüinos (viene con seaborn)
df_original = sns.load_dataset('penguins')

# Eliminar filas con valores nulos para simplificar
df = df_original.dropna().reset_index(drop=True)

print("📡 Transmisión recibida desde Estación Palmer...")
print("")
print(f"   📊 Registros de pingüinos cargados: {len(df)}")
print(f"   🏝️  Islas monitoreadas: {df['island'].nunique()}")
print(f"   🐧 Especies identificadas: {df['species'].nunique()}")
print("")
print("   Distribución por especie:")
for species in df['species'].unique():
    count = (df['species'] == species).sum()
    print(f"      • {species}: {count} individuos")

print("")
print("✅ Datos listos para análisis")

"""#Parte 1: Exploración del Dataset"""

# Veamos las primeras filas del dataset
print("🔍 Primeros 10 registros del campo:")
print("="*80)
df.head(10)

"""##Ejercicio 1.1: Estadísticas Básicas"""

print("Estadísticas Descriptivas")
print("="*80)
estadisticas = df.describe()
estadisticas

print("¿Cuál es el rango de masa corporal (body_mass_g) de los pingüinos?")
print("="*66)
print(f"Minima masa corporal: {estadisticas['body_mass_g']['min']}")
print(f"Maxima masa corporal: {estadisticas['body_mass_g']['max']}")
print(f"Rango de masa corporal: {estadisticas['body_mass_g']['max'] - estadisticas['body_mass_g']['min']}")

print("¿Cuál es la longitud promedio del pico (bill_length_mm)?")
print("="*56)
print(f"Longitud promedio del pico: {estadisticas['bill_length_mm']['mean']}")

print("¿Cuál es la longitud promedio de la aleta (flipper_length_mm)?")
print("="*62)
print(f"Longitud promedio de la aleta: {estadisticas['flipper_length_mm']['mean']}")

"""##Ejercicio 1.2 Estadísticas por Especie

"""

columnas_numericas = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']

grupo_especie = df.groupby('species')[columnas_numericas].mean()
grupo_especie.head(3)

print("Estadísticas por especie")
print("="*80)

for col in columnas_numericas:
  print(f"  {col}:")

  for especie in grupo_especie.index:
    valor = grupo_especie.loc[especie, col]
    print(f"    - {especie}: {valor}")

  print("\n")

print("¿Qué especie tiene el pico más largo en promedio?")
print("="*59)
print(f"La especie con el pico más largo en promedio es: {grupo_especie['bill_length_mm'].idxmax()}")

print("¿Qué especie tiene las aletas más largas?")
print("="*48)
print(f"La especie con las aletas más largas es: {grupo_especie['flipper_length_mm'].idxmax()}")

print("¿Qué especie es la más pesada?")
print("="*33)
print(f"La especie más pesada es: {grupo_especie['body_mass_g'].idxmax()}")

print("¿Qué especie tiene el pico más profundo?")
print("="*50)
print(f"La especie con el pico más profundo es: {grupo_especie['bill_depth_mm'].idxmax()}")

"""##Visualización"""

# ═══════════════════════════════════════════════════════════════════════════
# VISUALIZACIÓN: Diferencias entre especies
# ═══════════════════════════════════════════════════════════════════════════

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

variables = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
titulos = ['Longitud del Pico (mm)', 'Profundidad del Pico (mm)',
           'Longitud de Aleta (mm)', 'Masa Corporal (g)']

for ax, var, titulo in zip(axes.flat, variables, titulos):
    for species in df['species'].unique():
        subset = df[df['species'] == species]
        ax.hist(subset[var], alpha=0.6, label=species,
                color=COLORES_ESPECIES[species], bins=20, edgecolor='white')
    ax.set_xlabel(titulo)
    ax.set_ylabel('Frecuencia')
    ax.legend()
    ax.set_title(f'Distribución de {titulo} por Especie')

plt.tight_layout()
plt.savefig('pinguinos_distribucion.png', dpi=150, bbox_inches='tight')
plt.show()

# ═══════════════════════════════════════════════════════════════════════════
# VISUALIZACIÓN: Scatter plot para encontrar fronteras de decisión
# ═══════════════════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Gráfica 1: Pico (longitud vs profundidad)
for species in df['species'].unique():
    subset = df[df['species'] == species]
    axes[0].scatter(subset['bill_length_mm'], subset['bill_depth_mm'],
                   c=COLORES_ESPECIES[species], label=species, alpha=0.7, s=60)
axes[0].set_xlabel('Longitud del Pico (mm)')
axes[0].set_ylabel('Profundidad del Pico (mm)')
axes[0].set_title('Dimensiones del Pico por Especie')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Gráfica 2: Aleta vs Masa
for species in df['species'].unique():
    subset = df[df['species'] == species]
    axes[1].scatter(subset['flipper_length_mm'], subset['body_mass_g'],
                   c=COLORES_ESPECIES[species], label=species, alpha=0.7, s=60)
axes[1].set_xlabel('Longitud de Aleta (mm)')
axes[1].set_ylabel('Masa Corporal (g)')
axes[1].set_title('Aleta vs Masa por Especie')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('pinguinos_scatter.png', dpi=150, bbox_inches='tight')
plt.show()

"""#Parte 2: Diseño de Reglas de Clasificación

##Ejercicio 2.1: Doumenta tu estrategia

1. ¿Qué variable(s) usarás para separar primero una especie de las otras?
Considero que la ideal para separar a la primer especie va a ser la longitud de la aleta *flipper_length_mm* ya que hace una clara diferencia entre Gentoo y las otras 2 especies. Ahora para poder hacer una diferencia entre Adelie y Chinstrap sería con la longitud del pico *bill_length_mm*, aquí se ve una clara división entre estas 2 especies.


2. ¿Qué umbral(es) numérico(s) planeas usar? (ej: "si aleta > 210")

* Para la aleta planeo lo siguiente: Si aleta > 208 entonces es un Gentoo

* Si la longitud del pico < 45 será Adelie, de lo contrario será Chinstrap


3. ¿Cuál especie crees que será más fácil de identificar? ¿Por qué?
Creo será la de Gentoo ya que está visualmente más separado de los demás

4. ¿Cuál especie crees que será más difícil? ¿Por qué?
Chinstrap ya que en todas las gráficas e histogramas sus datos empatan con los de las otras especies.

##Ejercicio 2.2: Diseño de reglas
"""

def clasificador_humano(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g):


    if flipper_length_mm > 208:
         return "Gentoo"
    elif bill_length_mm < 45:
         return "Adelie"
    else:
         return "Chinstrap"

print("🧪 Prueba de tu clasificador humano:")
print("="*60)

# Casos de prueba (valores típicos de cada especie)
casos_prueba = [
    # [bill_length, bill_depth, flipper_length, body_mass, especie_real]
    [39.1, 18.7, 181, 3750, "Adelie"],
    [46.5, 17.9, 192, 3500, "Chinstrap"],
    [46.1, 13.2, 211, 4500, "Gentoo"],
]

print(f"{'Pico L':>8} {'Pico D':>8} {'Aleta':>8} {'Masa':>8} │ {'Real':>12} {'Tu Pred':>12} {'¿Correcto?':>12}")
print("-" * 80)

for caso in casos_prueba:
    pred = clasificador_humano(caso[0], caso[1], caso[2], caso[3])
    real = caso[4]
    correcto = "✅" if pred == real else "❌"
    print(f"{caso[0]:>8.1f} {caso[1]:>8.1f} {caso[2]:>8} {caso[3]:>8} │ {real:>12} {str(pred):>12} {correcto:>12}")

"""#Parte 3: Evaluación del Clasificador Humano

##Ejercicio 3.1: Prepara los datos
"""

X = df[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']]
y = df['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"📊 División de datos:")
print(f"   Entrenamiento: {len(X_train)} pingüinos")
print(f"   Prueba: {len(X_test)} pingüinos")

"""##Ejercicio 3.2: Evaluar Clasificador"""

predicciones_humano = []

for idx, row in X_test.iterrows():
    pred = clasificador_humano(
        row['bill_length_mm'],
        row['bill_depth_mm'],
        row['flipper_length_mm'],
        row['body_mass_g']
    )
    predicciones_humano.append(pred)

accuracy_humano = accuracy_score(y_test, predicciones_humano)

print("╔═══════════════════════════════════════════════════════════════╗")
print("║           🧠 RESULTADOS DEL CLASIFICADOR HUMANO 🧠           ║")
print("╠═══════════════════════════════════════════════════════════════╣")
print(f"║   Accuracy: {accuracy_humano:.2%}                                            ║")
print(f"║   Aciertos: {int(accuracy_humano * len(y_test))} de {len(y_test)} pingüinos                                ║")
print("╚═══════════════════════════════════════════════════════════════╝")

print("\n📋 Matriz de Confusión - Clasificador Humano:")
print("="*50)

cm_humano = confusion_matrix(y_test, predicciones_humano, labels=['Adelie', 'Chinstrap', 'Gentoo'])

plt.figure(figsize=(8, 6))
sns.heatmap(cm_humano, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Adelie', 'Chinstrap', 'Gentoo'],
            yticklabels=['Adelie', 'Chinstrap', 'Gentoo'])
plt.xlabel('Predicción del Humano')
plt.ylabel('Especie Real')
plt.title('Matriz de Confusión - Clasificador Humano')
plt.tight_layout()
plt.savefig('confusion_humano.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 Reporte Detallado:")
print(classification_report(y_test, predicciones_humano))

"""1. ¿Qué especie clasificaste mejor?
Adelie y Chinstrap, ambas con solo un error

2. ¿Qué especie te dio más problemas? ¿Por qué crees que pasó?
Aunque dije que era la más sencilla de separar fue Gentoo, considero que fue porque en la frontera de la longitud de la aleta habia alguna que otra muestra de otras especies, entonces esos outliers fueron los que afectaron un poco.

3. ¿Cuántos pingüinos clasificaste incorrectamente?
Fueron 6 pingüinos, 1 de Adelie, 1 de Chinstrap y 4 de Gentoo

#Parte 4: El Clasificador de Machine Learning

##Ejercicio 4.1: Modelo
"""

modelo_ml = DecisionTreeClassifier(random_state=42)

modelo_ml.fit(X_train, y_train)

print("✅ Modelo de Machine Learning entrenado!")
print(f"   Profundidad del árbol: {modelo_ml.get_depth()}")
print(f"   Número de hojas: {modelo_ml.get_n_leaves()}")

"""##Ejercicio 4.2: Evaluación de Modelo ML"""

predicciones_ml = modelo_ml.predict(X_test)

accuracy_ml = accuracy_score(y_test, predicciones_ml)

print("╔═══════════════════════════════════════════════════════════════╗")
print("║         🤖 RESULTADOS DEL CLASIFICADOR ML 🤖                 ║")
print("╠═══════════════════════════════════════════════════════════════╣")
print(f"║   Accuracy: {accuracy_ml:.2%}                                            ║")
print(f"║   Aciertos: {int(accuracy_ml * len(y_test))} de {len(y_test)} pingüinos                                ║")
print("╚═══════════════════════════════════════════════════════════════╝")

# Matriz de confusión del modelo ML
print("\n📋 Matriz de Confusión - Modelo ML:")
print("="*50)

cm_ml = confusion_matrix(y_test, predicciones_ml, labels=['Adelie', 'Chinstrap', 'Gentoo'])

plt.figure(figsize=(8, 6))
sns.heatmap(cm_ml, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Adelie', 'Chinstrap', 'Gentoo'],
            yticklabels=['Adelie', 'Chinstrap', 'Gentoo'])
plt.xlabel('Predicción del Modelo ML')
plt.ylabel('Especie Real')
plt.title('Matriz de Confusión - Modelo ML')
plt.tight_layout()
plt.savefig('confusion_ml.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 Reporte Detallado:")
print(classification_report(y_test, predicciones_ml))

from sklearn.tree import plot_tree

plt.figure(figsize=(20, 10))
plot_tree(
    modelo_ml,
    feature_names=['bill_length', 'bill_depth', 'flipper_length', 'body_mass'],
    class_names=['Adelie', 'Chinstrap', 'Gentoo'],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.title('Árbol de Decisión Aprendido por la Máquina', fontsize=16)
plt.tight_layout()
plt.savefig('arbol_pinguinos.png', dpi=150, bbox_inches='tight')
plt.show()

"""#Parte 5: Batalla Final"""

# ═══════════════════════════════════════════════════════════════════════════
# COMPARACIÓN FINAL
# ═══════════════════════════════════════════════════════════════════════════

print("")
print("╔═══════════════════════════════════════════════════════════════════════════╗")
print("║                                                                           ║")
print("║            ⚔️  BATALLA FINAL: HUMANO VS MÁQUINA ⚔️                       ║")
print("║                                                                           ║")
print("╠═══════════════════════════════════════════════════════════════════════════╣")
print("║                                                                           ║")
print(f"║   🧠 CLASIFICADOR HUMANO:     {accuracy_humano:.2%} accuracy                             ║")
print(f"║      Aciertos: {int(accuracy_humano * len(y_test)):2d}/{len(y_test)} pingüinos                                            ║")
print("║                                                                           ║")
print(f"║   🤖 CLASIFICADOR ML:         {accuracy_ml:.2%} accuracy                             ║")
print(f"║      Aciertos: {int(accuracy_ml * len(y_test)):2d}/{len(y_test)} pingüinos                                            ║")
print("║                                                                           ║")
print("╠═══════════════════════════════════════════════════════════════════════════╣")

diferencia = accuracy_ml - accuracy_humano

if diferencia > 0:
    print("║                                                                           ║")
    print("║                     🏆 GANADOR: LA MÁQUINA 🏆                            ║")
    print(f"║                     Ventaja: +{diferencia:.2%}                                       ║")
    print("║                                                                           ║")
elif diferencia < 0:
    print("║                                                                           ║")
    print("║                     🏆 GANADOR: EL HUMANO 🏆                              ║")
    print(f"║                     Ventaja: +{-diferencia:.2%}                                   ║")
    print("║                                                                           ║")
else:
    print("║                                                                           ║")
    print("║                        🤝 EMPATE TÉCNICO 🤝                               ║")
    print("║                                                                           ║")

print("╚═══════════════════════════════════════════════════════════════════════════╝")

# Gráfica comparativa
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Gráfica 1: Barras de accuracy
clasificadores = ['Humano', 'Máquina (ML)']
accuracies = [accuracy_humano * 100, accuracy_ml * 100]
colores_barras = ['#FF6B6B', '#4ECDC4']

bars = axes[0].bar(clasificadores, accuracies, color=colores_barras, edgecolor='white', linewidth=2)
axes[0].set_ylabel('Accuracy (%)')
axes[0].set_title('Comparación de Accuracy', fontweight='bold')
axes[0].set_ylim(0, 105)
for bar, acc in zip(bars, accuracies):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                f'{acc:.1f}%', ha='center', va='bottom', fontsize=14, fontweight='bold')

# Gráfica 2: Matrices de confusión lado a lado (Humano)
sns.heatmap(cm_humano, annot=True, fmt='d', cmap='Oranges', ax=axes[1],
            xticklabels=['A', 'C', 'G'], yticklabels=['A', 'C', 'G'])
axes[1].set_title('Matriz Humano', fontweight='bold')
axes[1].set_xlabel('Predicción')
axes[1].set_ylabel('Real')

# Gráfica 3: Matriz ML
sns.heatmap(cm_ml, annot=True, fmt='d', cmap='Blues', ax=axes[2],
            xticklabels=['A', 'C', 'G'], yticklabels=['A', 'C', 'G'])
axes[2].set_title('Matriz ML', fontweight='bold')
axes[2].set_xlabel('Predicción')
axes[2].set_ylabel('Real')

plt.suptitle('🐧 Batalla de Pingüinos: Humano vs Máquina 🐧', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('batalla_final.png', dpi=150, bbox_inches='tight')
plt.show()

resultados = X_test.copy()
resultados['especie_real'] = y_test.values
resultados['pred_humano'] = predicciones_humano
resultados['pred_ml'] = predicciones_ml
resultados['error_humano'] = resultados['especie_real'] != resultados['pred_humano']
resultados['error_ml'] = resultados['especie_real'] != resultados['pred_ml']

# Mostrar errores del humano
errores_humano = resultados[resultados['error_humano']]
print(f"❌ Errores del clasificador HUMANO ({len(errores_humano)} casos):")
print("="*80)
if len(errores_humano) > 0:
    print(errores_humano[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm',
                          'body_mass_g', 'especie_real', 'pred_humano']].to_string())
else:
    print("¡Ningún error! 🎉")

errores_ml = resultados[resultados['error_ml']]
print(f"\n❌ Errores del clasificador ML ({len(errores_ml)} casos):")
print("="*80)
if len(errores_ml) > 0:
    print(errores_ml[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm',
                      'body_mass_g', 'especie_real', 'pred_ml']].to_string())
else:
    print("¡Ningún error! 🎉")

"""##Ejercicio 5.2: Reflexión Final

1. ¿Quién ganó la batalla y por cuánto?
Ganó la maquiná por un 4.48%

2. ¿Qué errores cometiste que la máquina no cometió? (o viceversa) Los errores que cometí y que la máquina no fue en los siguientes registros
* 251 era Gentoo y predije Adelie
* 168 era Chinstrap y predije Adelie
* 269 era Gentoo y predije Adelie

3. ¿Las reglas del árbol de decisión se parecen a las tuyas? ¿Usó las mismas variables?
Las dos primeras reglas si uso las mismas variables aunque con valores distintos, a partir de ahi el arbol ya estudia demasiadas variables más.

4. ¿Cuál es la principal ventaja de usar Machine Learning sobre reglas manuales?
Obtiene mucha más información que la que nosotros como humanos podriamos notar o procesar, gracias a esto con ML el modelo aprende y reconoce patrones complejos mejorando su efectividad.

5. ¿Qué harías diferente si pudieras volver a diseñar tus reglas?
Probablemente considerar más variables para poder asegurarme más sobre a que especie pertenece cada uno de los registros.

#BONUS
"""

def clasificador_humano_optimo(bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g):

    if flipper_length_mm <= 207.5:

        if bill_length_mm <= 43.35:

            if bill_length_mm <= 42.35:

                if bill_depth_mm <= 16.65:

                    if bill_length_mm <= 39.5:
                        return "Adelie"
                    else:
                        return "Chinstrap"

                else:
                    return "Adelie"

            else:
                if flipper_length_mm <= 189.5:
                    return "Chinstrap"
                else:
                    return "Adelie"

        else:
            if body_mass_g <= 4125:
                return "Chinstrap"
            else:
                if bill_length_mm <= 45.9:
                    return "Adelie"
                else:
                    return "Chinstrap"

    else:
        if bill_depth_mm <= 17.65:
            return "Gentoo"
        else:
            if bill_length_mm <= 46.55:
                return "Adelie"
            else:
                return "Chinstrap"

print("🧪 Prueba de tu clasificador humano:")
print("="*60)

# Casos de prueba (valores típicos de cada especie)
casos_prueba = [
    # [bill_length, bill_depth, flipper_length, body_mass, especie_real]
    [39.1, 18.7, 181, 3750, "Adelie"],
    [46.5, 17.9, 192, 3500, "Chinstrap"],
    [46.1, 13.2, 211, 4500, "Gentoo"],
]

print(f"{'Pico L':>8} {'Pico D':>8} {'Aleta':>8} {'Masa':>8} │ {'Real':>12} {'Tu Pred':>12} {'¿Correcto?':>12}")
print("-" * 80)

for caso in casos_prueba:
    pred = clasificador_humano_optimo(caso[0], caso[1], caso[2], caso[3])
    real = caso[4]
    correcto = "✅" if pred == real else "❌"
    print(f"{caso[0]:>8.1f} {caso[1]:>8.1f} {caso[2]:>8} {caso[3]:>8} │ {real:>12} {str(pred):>12} {correcto:>12}")

predicciones_humano_v2 = []

for idx, row in X_test.iterrows():
    pred = clasificador_humano_optimo(
        row['bill_length_mm'],
        row['bill_depth_mm'],
        row['flipper_length_mm'],
        row['body_mass_g']
    )
    predicciones_humano_v2.append(pred)

accuracy_humano_v2 = accuracy_score(y_test, predicciones_humano_v2)

print("╔═══════════════════════════════════════════════════════════════╗")
print("║        📈 RESULTADOS DEL CLASIFICADOR MEJORADO 📈             ║")
print("╠═══════════════════════════════════════════════════════════════╣")
print(f"║   Versión 1: {accuracy_humano:.2%}                                           ║")
print(f"║   Versión 2: {accuracy_humano_v2:.2%}                                           ║")
print(f"║   Mejora:    {(accuracy_humano_v2 - accuracy_humano):.2%}                                            ║")
print("╚═══════════════════════════════════════════════════════════════╝")

if accuracy_humano_v2 > accuracy_humano:
    print("\n🎉 ¡Excelente! Tu clasificador mejoró.")
else:
    print("\n🤔 Hmm, no hubo mejora. ¿Puedes intentar otros cambios?")

print("\n📋 Matriz de Confusión - Clasificador Humano:")
print("="*50)

cm_humano = confusion_matrix(y_test, predicciones_humano_v2, labels=['Adelie', 'Chinstrap', 'Gentoo'])

plt.figure(figsize=(8, 6))
sns.heatmap(cm_humano, annot=True, fmt='d', cmap='Oranges',
            xticklabels=['Adelie', 'Chinstrap', 'Gentoo'],
            yticklabels=['Adelie', 'Chinstrap', 'Gentoo'])
plt.xlabel('Predicción del Humano')
plt.ylabel('Especie Real')
plt.title('Matriz de Confusión - Clasificador Humano')
plt.tight_layout()
plt.savefig('confusion_humano.png', dpi=150, bbox_inches='tight')
plt.show()

print("\n📊 Reporte Detallado:")
print(classification_report(y_test, predicciones_humano_v2))

"""Cambios realizados: En esta versión mejorada del clasificador se ajustaron los umbrales y se incorporaron variables adicionales. Primero, la identificación de Gentoo dejó de depender únicamente de la longitud de la aleta y ahora combina flipper_length_mm > 207.5 con bill_depth_mm <= 17.5, reduciendo falsos positivos al exigir coherencia en ambas características.

También se refinó el umbral para Adelie, ajustando bill_length_mm a <= 43.5, ya que con un mejor análisis noté que la frontera real estaba más cerca de ese valor que del corte anterior. Además, se incorporó body_mass_g como criterio auxiliar para identificar Chinstrap en casos intermedios, aprovechando que suele tener menor masa que Gentoo. Finalmente, se añadió una regla con bill_depth_mm > 17.5 para resolver ambigüedades entre Adelie y Chinstrap.

En conjunto, los cambios no aumentan la complejidad de forma arbitraria, sino que afinan las fronteras de decisión utilizando información estadística real del modelo entrenado, buscando mejorar la precisión manteniendo una estructura basada en reglas claras.
"""